### ISSUE TITLE
can not build: ./main.go:147: undefined: ssautil.MainPackages

### ISSUE THREAD

**Issue by wgliang** [TrueFurby/go-callvis#10]
can not build: ./main.go:147: undefined: ssautil.MainPackages

**Comment by wgliang** [comment]
not find ssautil.MainPackages function!

**Comment by TrueFurby** [comment]
This is probably happening due different version of `golang.org/x/tools`.

So, I have added [dep](https://github.com/golang/dep) for handling dependencies.

Now, try running:

```sh
go get -u github.com/TrueFurby/go-callvis
cd $GOPATH/src/github.com/TrueFurby/go-callvis && make
```
