### ISSUE TITLE
Makefile assumes GOPATH has one directory

### ISSUE THREAD

**Issue by AndrewWPhillips** [TrueFurby/go-callvis#18]
I get thios error when I run make:

>Fatal: Unable to execute command: L:\Dev...;D:\Golang/bin/dep

I think this is becuase the makefile uses $(GOPATH) as if it contains a single directory
> dep:
> 	$(GOPATH)/bin/dep ensure

**Comment by TrueFurby** [comment]
I will probably make the *dep* target to run `dep ensure` and relying on the users to have `$GOPATH/bin` in their `PATH`.

**Comment by TrueFurby** [comment]
Try it now please.
