### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by andersfylling** [TrueFurby/go-callvis#20]
go version: `go version go1.10 linux/amd64`

command: `make`

output:
```go get -u github.com/golang/dep/cmd/dep
dep ensure
make: dep: Command not found
make: *** [Makefile:10: dep] Error 127
```

**Comment by TrueFurby** [comment]
Is that the entier output? The `make` should automatically call `make get-deps`, although you can try running it separately.

**Comment by jakeschurch** [comment]
Had the same issue, calling `make get-deps` worked for me

**Comment by jakeschurch** [comment]
having same error

**Comment by TrueFurby** [comment]
Could you post log of the command you are trying to run and the output?

**Comment by jakeschurch** [comment]
go version: `go version go1.9.2 linux/amd64`

command: `make`

output:
```
go get -u github.com/golang/dep/cmd/dep
dep ensure
make: dep: Command not found
Makefile:10: recipe for target 'dep' failed
make: *** [dep] Error 127
```

Looks like this is the same output that @andersfylling is getting

**Comment by jakeschurch** [comment]
was hacking around on the Makefile to see if I could fix it myself

Adding ` GOBIN := $(shell go env GOBIN) ` right below `GOARCH` decleration and changing `dep ensure` to `$(GOBIN)/./dep ensure ` seemed to do the trick for me @TrueFurby

**Comment by TrueFurby** [comment]
Do you have your `bin` (from GOPATH/bin) in the `PATH` environment variable?

**Comment by jakeschurch** [comment]
My GOPATH was separate from my GOROOT env variable; causing the issues. 

All set now.
