### ISSUE TITLE
go-callvis for quorum packages

### ISSUE THREAD

**Issue by Richcardin** [TrueFurby/go-callvis#22]
git clone https://github.com/jpmorganchase/quorum.git
Iam trying this command
go-callvis -focus upgrade -group pkg,type -limit github.com/jpmorganchase/quorum github.com/jpmorganchase/quorum

output- 
go-callvis: cannot find package "upgrade" in any of:
        /usr/local/go/src/upgrade (from $GOROOT)
        /home/ubuntu/go/src/upgrade (from $GOPATH)

**Comment by sjeeva** [comment]
incidentally I also stumbled on the same issue!! Any thoughts on how to resolve this?

**Comment by TrueFurby** [comment]
Target needs to be a program. `github.com/jpmorganchase/quorum` doesn't seem to be a program. Try one of the programs in cmd folder.

**Comment by MichaelMure** [comment]
@TrueFurby any plan to support libraries ?

**Comment by TrueFurby** [comment]
Main package (program) is required for the analysis used, because all the calls in the callgraph tree begins in main (and inits).

In package you don't really know what will be called, since it's just a package without some start point. Program that will use the package can call anything or nothing.

**Comment by MichaelMure** [comment]
Instead of a single entry point (`main()`) you could have multiple entry points (every exported function).

But I understand it might not be easy or even possible depending on the code you have. Just stating that it would be very helpful to understand a codebase.

**Comment by TrueFurby** [comment]
You easily do that by creating a simple program and placing all the calls you are interested in, for example exported functions of some package, and running go-callvis on that program.
