### ISSUE TITLE
Cannot visualize github.com/alecthomas/gozmq

### ISSUE THREAD

**Issue by iselind** [TrueFurby/go-callvis#27]
github.com/alecthomas/gozmq seems problematic for go-callvis to handle. I'm guessing because gozmq require cgo. 

```bash
# % is my prompt
# Get the source, this works great, i have the libzmq3-dev deb-package installed on my machine
% go get -tags zmq_3_x github.com/alecthomas/gozmq
# The following command complain that various symbols are not declared. They are declared, but in the C part of package
% go-callvis github.com/alecthomas/gozmq
# go-callvis show the help pages when i do the following, missing feature?
% go-callvis -tags zmq_3_x github.com/alecthomas/gozmq
```
Is there any work ongoing to fix this?

**Comment by TrueFurby** [comment]
I'll look into this and let you know. I also accept PR if you'd like to implement this.

**Comment by TrueFurby** [comment]
Hey @iselind the `-tags` flag is included in the upcoming changes. You can find it in opened PR here: https://github.com/TrueFurby/go-callvis/pull/29 with several other improvements.

The call graph output is now served via HTTP server in SVG format and you can click on packages to change focus.
