### ISSUE TITLE
focus on multiple packages

### ISSUE THREAD

**Issue by andy-miracl** [TrueFurby/go-callvis#28]
We have a library that is separated into many sub-packages in deeply nested folders in the repo. We would like to visualize this entire library, i.e. we would like to focus on all these sub-packages. How can we do this?

Thanks

Andy

**Comment by andy-miracl** [comment]
Looking at the code, our problem seems to stem from the fact that the `-focus` option defaults to `main`. I can circumvent this by explicitly setting `-focus ""`, then using appropriate `-limit` to keep the size down.

**Comment by TrueFurby** [comment]
I used empty focus by default to prevent huge outputs. What is needed is more filtering options to minimize this.

**Comment by TrueFurby** [comment]
@andy-miracl Hey, I made a PR with some enhancements that might make it more useful for you. The output is now serve via HTTP server in SVG format and you can click on packages to change focus.
https://github.com/TrueFurby/go-callvis/pull/29
The PR will need some more README changes before I merge it, but you could try it already, let me know if you find any issues.
