### ISSUE TITLE
v0.4 is not a semantic version tag, is ignored by go modules

### ISSUE THREAD

**Issue by pwaller** [TrueFurby/go-callvis#44]
Unfortunately if you use `go get -u github.com/TrueFurby/go-callvis` on go 1.12 with modules enabled, it fetches version v0.3.5, which is the latest semantic version tag it can find.

The fix would be to tag v0.4.0, or some later version.

**Comment by ondrej-fabry** [comment]
I created v0.4.0 tag: https://github.com/TrueFurby/go-callvis/releases/tag/v0.4.0
