### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by Allenxuxu** [TrueFurby/go-callvis#46]
2019/04/26 10:45:04 http serving at http://localhost:7878
2019/04/26 10:45:05 converting dot to svg..
2019/04/26 10:45:05 unable to find program 'dot', please install it or check your PATH

**Comment by TrueFurby** [comment]
Please see [Requirements](https://github.com/TrueFurby/go-callvis#requirements).

**Comment by Allenxuxu** [comment]
Thanks @TrueFurby
