### ISSUE TITLE
Not looking for packages in 'mod' location

### ISSUE THREAD

**Issue by christopinka** [TrueFurby/go-callvis#48]
Error is 

` could not import github.com/aws/aws-lambda-go/events (cannot find package "github.com/aws/aws-lambda-go/events" in any of:
        /usr/local/Cellar/go/1.12.1/libexec/src/github.com/aws/aws-lambda-go/events (from $GOROOT)
        /Users/christopinka/go/src/github.com/aws/aws-lambda-go/events (from $GOPATH))
`

All dependencies are in  /Users/christopinka/go/pkg/mod as module versions however.

**Comment by Antonboom** [comment]
+1

**Comment by TrueFurby** [comment]
This should be fixed by #49
