### ISSUE TITLE
Startup problems?

### ISSUE THREAD

**Issue by davmaz** [TrueFurby/go-callvis#5]
Hello -- looks like a great tool. However, after following your install procedure, when I run go-callvis using your example I get this:
 go-callvis -focus upgrade -limit github.com/syncthing/syncthing github.com/syncthing/syncthing/cmd/syncthing | dot -Tpng -o syncthing_focus.png
/opt/Projects/Golang/src/github.com/syncthing/syncthing/cmd/syncthing/gui_statics.go:37:13: Assets not declared by package auto
/opt/Projects/Golang/src/github.com/syncthing/syncthing/cmd/syncthing/gui_statics.go:44:20: Assets not declared by package auto
/opt/Projects/Golang/src/github.com/syncthing/syncthing/cmd/syncthing/gui_statics.go:44:20: cannot range over auto.Assets() (invalid operand)
go-callvis: couldn't load packages due to errors: github.com/syncthing/syncthing/cmd/syncthing

Am I doing something wrong?

**Comment by TrueFurby** [comment]
The syncthing program uses customized build process. Try running this before go-callvis:

```
cd $GOPATH/src/github.com/syncthing/syncthing
./build.sh
```

**Comment by TrueFurby** [comment]
I will close this issue. If you still have problems, please reopen it or create new one.

**Comment by yhcd** [comment]
please add  syncthing build command on examples/Readme.md

**Comment by ruudk** [comment]
Had the same issue, so decided to add it to the readme. https://github.com/TrueFurby/go-callvis/pull/34
