### ISSUE TITLE
packages contain errors

### ISSUE THREAD

**Issue by BluceHuang** [TrueFurby/go-callvis#60]
go-callvis.exe --debug -nostd ./resbroker/broker/                                                                                                            D:\Go\src\runtime\cgo\cgo.go:31:8: could not import C (no metadata for C)
D:\GOPATH\pkg\mod\github.com\mattn\go-sqlite3@v2.0.2+incompatible\backup.go:16:8: could not import C (no metadata for C)
17:15:55.715345 packages contain errors

**Comment by BluceHuang** [comment]
I resole this by installing mingw64 on my computer

**Comment by Arrkwen** [comment]
on the ubuntu system,it does not work after install mingw64.  besides, i set the ignore flag to ignore the package include 'c' api. How can I solve the problem?
