### ISSUE TITLE
Can  go-callvis run on the windows

### ISSUE THREAD

**Issue by saxon17** [TrueFurby/go-callvis#8]
after run go get cmd 

This one 
go-callvis [OPTIONS] <main pkg> | dot -Tpng -o output.png
seems get problem

any other Path things should be set on windows ?

**Comment by TrueFurby** [comment]
I don't really use windows, but I don't think their shell supports piping commands (the "|" character between go-callvis and dot). 

Although, you could run just the go-callvis without the rest and use the output from it in some Graphviz program that will generate the image. 

- You can try downloading  windows version from the official site: 

    http://www.graphviz.org/Download_windows.php

- Or you use some online tools to make it:

    http://www.webgraphviz.com/
    http://sandbox.kidstrythisathome.com/erdos/


Hope this helps!

**Comment by saxon17** [comment]
HI TrueFurby,
    go-callvis cmd cant not be run after  I download it use go get...(both on Mac sys and Windows, all prompting “can not find this go-callvis cmd".
    any other steps should be setup?  
    I'm fresh new to golang, hope this things will not bother you.

**Comment by TrueFurby** [comment]
Are you able to run any other programs built using `go get`?

**Comment by saxon17** [comment]
can not run..

**Comment by saxon17** [comment]
![image](https://cloud.githubusercontent.com/assets/7868631/23576306/da9bb540-00dc-11e7-9c73-f37cfcbdd077.png)
The document structure on windows after run go get commend

**Comment by saxon17** [comment]
Maybe it has not been built?

**Comment by TrueFurby** [comment]
check in `E:/go_programming/bin/`

**Comment by TrueFurby** [comment]
I will close this due inactivity. Feel free to reopen if you still have some issues.

**Comment by wilmerkrisp** [comment]
this is not working in windows
